name: makc
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #==================== FIREBASE ====================#
  firebase_core: ^3.1.1
  firebase_core_platform_interface: ^6.0.0
  firebase_messaging: ^15.0.0
  firebase_performance: ^0.10.1+10
  flutter_local_notifications: ^18.0.1

  #==================== STATE MANAGEMENT ====================#
  get: ^4.6.6

  #==================== NETWORK ====================#
  http:

  #==================== UI & UX ====================#
  lottie: ^3.3.0
  flutter_svg: ^2.0.12
  iconly: ^1.0.1

  #==================== MEDIA & PLAYER ====================#
  cached_network_image: ^3.3.1

  #==================== LOCAL STORAGE ====================#
  get_storage: ^2.1.1

  #==================== UTILITIES ====================#
  intl: ^0.20.2
  hugeicons: ^1.1.5
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/your_community_images/
    - assets/images/onboarding/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
